name: http-server-projeto-korp

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http-server-korp
    expose:
      - "8080"
    networks:
      - korp-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-korp
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - korp-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-korp
    depends_on:
      - app
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - korp-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-korp
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - korp-network
    restart: unless-stopped

networks:
  korp-network:
    name: korp-network
    driver: bridge